version: '3.8'

services:

  nginx:
    image: nginx:1.23-alpine
    container_name: web
    restart: always
    ports:
      - '8000:80'
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks:
      - portfolio-archive

networks:
  portfolio-archive:
